//! An example of types generated by [flagnum](crate).
//!
//! Be aware that this module is only available for documentation purposes and is
//! not included outside of documentation builds.
//!
//! The following code was used to generate the types below:
//!
//! ```rust
#![doc = include_str!("example/weekdays.rs")]
//! ```

mod weekdays;
pub use weekdays::*;